fix with nc17

diff --git a/misc/ncserver b/misc/ncserver
--- a/misc/ncserver
+++ b/misc/ncserver
@@ -5,7 +5,7 @@ HOST_IP=$(ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n')
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 if [ -f "$DIR/.env" ]; then
-	export $(cat "$DIR/.env" | grep -v ^# | xargs)
+    export $(cat "$DIR/.env" | grep -v ^# | xargs)
 fi
 SQL=$1
 PORT=`python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'`
@@ -21,6 +21,7 @@ mkdir -p "$WORKDIR/$NAME/integration/output"
 mkdir -p "$WORKDIR/$NAME/integration/work"
 mkdir -p "$WORKDIR/$NAME/integration/vendor"
 touch "$WORKDIR/$NAME/integration/composer.lock"
+touch "$WORKDIR/$NAME/config/CAN_INSTALL"
 
 mkdir -p "$WORKDIR/composer/cache"
 
@@ -28,8 +29,8 @@ PHP_VERSION=$2
 PHP_VERSION=${PHP_VERSION:-5}
 
 if [ "$PHP_VERSION" != "5" ] && [ "$PHP_VERSION" != "7" ]; then
-	echo "invalid php version"
-	exit
+    echo "invalid php version"
+    exit
 fi;
 
 
@@ -41,14 +42,16 @@ LINK=""
 EXTRA_ENV="-e XDEBUG_CONFIG=remote_host=$HOST_IP -e PHP_IDE_CONFIG=serverName=docker"
 EXTRA_CONTAINERS=""
 
+LINK_BLACKFIRE=""
+
 for arg in "$@"
 do
-	if [ "$arg" = "s3" ]; then
-		docker run --name "$NAME-s3" -d lphoward/fake-s3
-		LINK="$LINK --link $NAME-s3:s3"
-		EXTRA_CONTAINERS="$EXTRA_CONTAINERS,$NAME-s3"
-		EXTRA_ENV="$EXTRA_ENV -e S3=1"
-	fi
+    if [ "$arg" = "s3" ]; then
+        docker run --name "$NAME-s3" -d lphoward/fake-s3
+        LINK="$LINK --link $NAME-s3:s3"
+        EXTRA_CONTAINERS="$EXTRA_CONTAINERS,$NAME-s3"
+        EXTRA_ENV="$EXTRA_ENV -e S3=1"
+    fi
     if [ "$arg" = "swift" ] || [ "$arg" = "swiftv2" ]; then
         docker run --name "$NAME-swift" -d icewind1991/dockswift:nextcloud-ci
         LINK="$LINK --link $NAME-swift:swift --link $NAME-swift:keystone --link $NAME-swift:dockswift"
@@ -68,26 +71,26 @@ do
         EXTRA_CONTAINERS="$EXTRA_CONTAINERS,$NAME-azure"
         EXTRA_ENV="$EXTRA_ENV -e AZURE=1"
     fi
+    if [ "$arg" = "blackfire" ]; then
+        BLACKFIRE_RUNNING=$(docker inspect --format="{{ .State.Running }}" blackfire 2> /dev/null)
+        BLACKFIRE_EXIT_CODE=$?
+        if [ -z "$BLACKFIRE_SERVER_TOKEN" ] && [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then # we either need the blackfire config or already have an existing container
+            echo "Set \$BLACKFIRE_SERVER_TOKEN and \$BLACKFIRE_SERVER_ID to enable blackfire integration (https://blackfire.io/docs/integrations/docker)"
+        else
+            # ensure blackfire agent is running    
+            if [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then
+                docker run --name="blackfire" -d -e BLACKFIRE_SERVER_ID=$BLACKFIRE_SERVER_ID -e BLACKFIRE_SERVER_TOKEN=$BLACKFIRE_SERVER_TOKEN blackfire/blackfire
+            elif [ "$BLACKFIRE_RUNNING" == "false" ]; then
+                docker start blackfire
+            fi;    
+            sleep 5
+            BLACKFIRE_RUNNING=$(docker inspect --format="{{ .State.Running }}" blackfire 2> /dev/null)
+            if [ "$BLACKFIRE_RUNNING" == "true" ]; then    
+                LINK="$LINK --link blackfire:blackfire"
+            fi;
+        fi;
+    fi
 done
-
-BLACKFIRE_RUNNING=$(docker inspect --format="{{ .State.Running }}" blackfire 2> /dev/null)
-BLACKFIRE_EXIT_CODE=$?
-if [ -z "$BLACKFIRE_SERVER_TOKEN" ] && [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then # we either need the blackfire config or already have an existing container
-	echo "Set \$BLACKFIRE_SERVER_TOKEN and \$BLACKFIRE_SERVER_ID to enable blackfire integration (https://blackfire.io/docs/integrations/docker)"
-	LINK_BLACKFIRE=""
-else
-	# ensure blackfire agent is running
-	if [ $BLACKFIRE_EXIT_CODE -eq 1 ]; then
-		docker run --name="blackfire" -d -e BLACKFIRE_SERVER_ID=$BLACKFIRE_SERVER_ID -e BLACKFIRE_SERVER_TOKEN=$BLACKFIRE_SERVER_TOKEN blackfire/blackfire
-	elif [ "$BLACKFIRE_RUNNING" == "false" ]; then
-		docker start blackfire
-	fi;
-    sleep 2
-    BLACKFIRE_RUNNING=$(docker inspect --format="{{ .State.Running }}" blackfire 2> /dev/null)
-    if [ "$BLACKFIRE_RUNNING" == "true" ]; then
-    	LINK_BLACKFIRE="--link blackfire:blackfire"
-    fi;
-fi;
 
 WEBROOT="/var/www/html"
 DATAROOT="$WORKDIR/$NAME"
@@ -96,20 +99,20 @@ DOCKER_IMAGE="icewind1991/nextcloud-dev:$PHP_VERSION"
 #DOCKER_IMAGE="nc"
 
 if [ "$SQL" = "mysql" ]; then
-	docker run --name "$NAME-mysql" -e MYSQL_ROOT_PASSWORD=$SQL_PASS -e MYSQL_PASSWORD=owncloud -e MYSQL_USER=owncloud -e MYSQL_DATABASE=owncloud -d mysql:5.7
-	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-mysql:mysql" $LINK $EXTRA_ENV -e SQL=mysql $VOLUMES $DOCKER_IMAGE
-	echo "$NAME,$NAME-mysql$EXTRA_CONTAINERS"
+    docker run --name "$NAME-mysql" -e MYSQL_ROOT_PASSWORD=$SQL_PASS -e MYSQL_PASSWORD=owncloud -e MYSQL_USER=owncloud -e MYSQL_DATABASE=owncloud -d mysql:5.7
+    docker run --name $NAME -d -p $PORT:80 --link "$NAME-mysql:mysql" $LINK $EXTRA_ENV -e SQL=mysql $VOLUMES $DOCKER_IMAGE
+    echo "$NAME,$NAME-mysql$EXTRA_CONTAINERS"
 elif [ "$SQL" = "pgsql" ]; then
-	docker run --name "$NAME-pgsql" -e POSTGRES_PASSWORD=owncloud -e POSTGRES_USER=owncloud -e POSTGRES_DATABASE=owncloud -d postgres:latest
-	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-pgsql:pgsql" $LINK $EXTRA_ENV -e SQL=pgsql $VOLUMES $DOCKER_IMAGE
-	echo "$NAME,$NAME-pgsq$EXTRA_CONTAINERSl"
+    docker run --name "$NAME-pgsql" -e POSTGRES_PASSWORD=owncloud -e POSTGRES_USER=owncloud -e POSTGRES_DATABASE=owncloud -d postgres:latest
+    docker run --name $NAME -d -p $PORT:80 --link "$NAME-pgsql:pgsql" $LINK $EXTRA_ENV -e SQL=pgsql $VOLUMES $DOCKER_IMAGE
+    echo "$NAME,$NAME-pgsq$EXTRA_CONTAINERSl"
 elif [ "$SQL" = "oci" ]; then
-	docker run --name "$NAME-oci" -d wnameless/oracle-xe-11g
-	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE --link "$NAME-oci:oci" $LINK $EXTRA_ENV -e SQL=oci $VOLUMES $DOCKER_IMAGE
-	echo "$NAME,$NAME-oci$EXTRA_CONTAINERS"
+    docker run --name "$NAME-oci" -d wnameless/oracle-xe-11g
+    docker run --name $NAME -d -p $PORT:80 --link "$NAME-oci:oci" $LINK $EXTRA_ENV -e SQL=oci $VOLUMES $DOCKER_IMAGE
+    echo "$NAME,$NAME-oci$EXTRA_CONTAINERS"
 else
-	docker run --name $NAME -d -p $PORT:80 $LINK_BLACKFIRE $LINK $EXTRA_ENV -e SQL=sqlite $VOLUMES $DOCKER_IMAGE
-	echo "$NAME$EXTRA_CONTAINERS"
+    docker run --name $NAME -d -p $PORT:80 $LINK $EXTRA_ENV -e SQL=sqlite $VOLUMES $DOCKER_IMAGE
+    echo "$NAME$EXTRA_CONTAINERS"
 fi
 
 echo "Running on http://localhost:$PORT"
